### ISSUE TITLE
Small bug when running install script

### ISSUE THREAD

**Issue by moosmann** [dmpelt/pyastratoolbox#16]
Hi Daan,

I hope you're doing fine. How's your PhD doing?

To the actual issue:

When running the install script, the Cython-version checking fails on some platforms. We encountered this bug on two machines using Ubuntu 14.04 LTS.

Following error message occurs when running 'install.sh':

Traceback (most recent call last):
  File "builder.py", line 40, in <module>
    if StrictVersion(Cython.__version__)>=StrictVersion('0.13'):
  File "/usr/lib/python2.7/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/lib/python2.7/distutils/version.py", line 107, in parse
    raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '0.20.1post0

I quickly fixed the bug replacing following line in 'builder.py'
    if StrictVersion(Cython.__version__)>=StrictVersion('0.13'):
by
    if StrictVersion(Cython.__version__[0:4])>=StrictVersion('0.13'):

Best wishes,
Julian

**Comment by dmpelt** [comment]
Hi Julian,

Everything is going well! I hope you are doing fine too.

Thanks for reporting the build error. Someone else noticed this as well, and it has been updated in the master branch (see #10). So using the master branch of this github repository should fix the problem.

However, the Python interface has recently been merged into the main ASTRA toolbox code, and the first public release with the interface included should be released soon (in the next few weeks). The master branch of the [ASTRA git repository](https://github.com/astra-toolbox/astra-toolbox) is already updated, so I recommend using that until the next version has been released. It has a lot of other improvements and additions as well!

After the release of the next version of the ASTRA toolbox (with the Python interface included), I will update this repository, removing all code and adding a simple link to the main ASTRA repository.

Let me know if you have any problems with installing the toolbox.

Cheers,
Daan
